<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.0.0</Version>
        <Title>Wasp</Title>
        <Description>Lightweight state machine library for game
development</Description>
        <Authors>q-0q</Authors>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <LangVersion>12</LangVersion>
        <TargetFrameworks>net48;net471</TargetFrameworks>
        <RepositoryUrl>https://github.com/wasp-state-machine/wasp</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
        <Src Include="src/**/*.*" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
