<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.2</Version>
        <Title>Wasp</Title>
        <Description>Lightweight state machine library for game
development</Description>
        <Authors>q-0q</Authors>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
        <Src Include="src/**/*.*" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
